### PR TITLE
Escape userids part2

### PR DESCRIPTION
**Pull request by Half-Shot**
(There were also a handful of cleanups)

Not sure why I didn't describe what this was fixing. The intention of the change is to allow bridges to opt out of escaping their userids.

~~ Will fix #99 ~~

### CODE REVIEW

**Comment by AndrewJDR** [comment]
Running this on the imessage bridge. So far so good (fixes the issues there). Merge time? :)

**Comment by turt2live** [comment]
@Half-Shot what issue does this fix? I assume it doesn't fix itself.

**Comment by Half-Shot** [comment]
Errrrrr what was I smoking

**Comment by AndrewJDR** [comment]
it Fixes #98

**Pull request merged**
